config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'

  resources :docs
  authenticated :user do
   root "docs#index", as: "authenticated_root"
 end

  root 'welcome#index'
  get "password/reset", to: "password_reset#new"
  post "password/reset", to: "password_reset#new"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/doc.rb
class Doc < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :docs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/docs_controller.rb
class DocsController < ApplicationController
  before_action :find_doc, only: [:show, :edit, :update, :destroy]

  def index
    @docs = Doc.where(user_id: current_user)
  end

  def show

  end

  def new
    @doc = current_user.docs.build
  end

  def create
    @doc = current_user.docs.build(doc_params)

    if @doc.save
       redirect_to @doc
     else
       render 'new'
      end
  end

  def edit
    # code
  end

  def update
  if @doc.update(doc_params)
    redirect_to @doc
  else
    render 'edit'

    end
  end

  def destroy
   @doc.destroy
   redirect_to docs_path
  end

  private

  def find_doc
    @doc = Doc.find(params[:id])
  end

  def doc_params
    params.require(:doc).permit(:title, :content)
  end
end

app/controllers/password_resets_controller.rb
class PasswordResetsCotroller < ApplicationController
  def new
    # code
  end

  def create
     @user = User.find_by(email: params[:email])


  if @user.present?
    # Send Email
     PasswordMailer.with(user: @user).reset.deliver_later
    end
    redirect_to_root_path, notice: "If an acount with that email was found, we habe sent a link to reset your password "
 end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/docs_helper.rb
module DocsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/docs/_form.html.haml
= simple_form_for @doc do |f|
 = f.input :title, class: "button"
 = f.input :content, class: "button"
 = f.button :submit, class: "button"

app/views/docs/edit.html.haml
.wrapper_with_padding

  %h1 Edit doc!

  = render 'form'

  = link_to "Cancel", docs_path

app/views/docs/index.html.haml
.wrapper_with_padding
  %h1 Your Docs
  #docs.clearfix
    - unless @docs.blank?

      - @docs.each do |doc|
        %a{:href => (url_for [doc])}
          .doc
            %p.title= doc.title
            %p.date= "#{time_ago_in_words(doc.created_at)} ago"
            %p.content= truncate(doc.content, legnth:70)
            %hr

    - else
      %h2 Create Doc!
      %p Start Creating Documents and Organizing your life!
      %button= link_to "Create Doc", new_doc_path, class: "button"

app/views/docs/new.html.haml
.wrapper_with_padding
  %h1 New Doc!

  = render 'form'
  = link_to "Cancel", docs_path, class: "button"

app/views/docs/show.html.haml
.wrapper_with_padding
  #doc_show
    %h1.title= @doc.title
    %p= simple_format(@doc.content)
    .buttons
      = link_to "All Docs", docs_path, class: "button"
      = link_to "Fix Doc", edit_doc_path(@doc), class: "button"
      = link_to "Trash It", doc_path(@doc), method: :delete, data: { confirm: "Are you sure?"}, class: "button"

app/views/layouts/application.html.haml
%html
%head
  %title FileCabinet | Your life's work
  = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
  =  javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  = csrf_meta_tags

%body
  %header
    .header_inner
      = link_to "FileCabinet", root_path, id: "logo"

      %nav
        - if user_signed_in?
          = link_to "Create Doc", new_doc_path
          = link_to "Sign Out", destroy_user_session_path, method: :delete
        - else
          = link_to "Login", new_user_session_path, method: :create

  %p.notice= notice
  %p.alert= alert

  = yield

app/views/password_resets/new.html.erb
<h1>Forgot your Password</h1>

<%= form_with url: password_reset_path do |form| %>
  <div class="mb-3">
      <%= form.label :email %>
      <%= form.text_field :email, class: "form-control", placeholder: "@resource.unconfirmed_email" %>
  </div>
  <div class="mb-3">
    <%= form.submit "Reset Password", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/welcome/index.html.haml
#banner
    .banner_content
        %h1 File Cabinet
        %p Your life's work. Always organized.
        %button= link_to "Enter", new_user_registration_path

#callouts
    .callout_inner
        .wrapper
            .redhat.img
                %h2 Organize
                %p Lucas ipsum dolor sit amet hutt jade ogemite quinlan orus lumiya thisspias lorth moff tyranus. Teneniel dagobah naberrie sern. Jin'ha antilles jan piett er'kit barabel vuffi mon. Piett sluis elrood neimoidian. Qui-gonn shmi momaw bajic gavyn quadrinaros. Maul massa koon lepi ben. Cassio miraluka san unduli nosaurian zuggs gamorr. Ebe tarpals trianii mara gran max vella caamasi. Mod bane auril cb-99. Nahdar gran wroonian kast rahn priapulin irek sidious shadda. Noghri tierce tarpals cadavine togruta saleucami seerdon cathar balosar.

#bottom_cta
    .wrapper
        %h2 Go Ahead!
        %br/
        %button= link_to "Join Now", new_user_registration_path